name: Update & filter extensions repo (no NSFW)

on:
  workflow_dispatch:
  schedule:
    - cron: "12/30 * * * *"

permissions:
  contents: write

jobs:
  update_filter:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Save local README
        run: |
          if [ -f README.md ]; then
            cp README.md /tmp/README.local
          fi

      - name: Fetch upstream repo
        run: |
          git remote add upstream https://github.com/keiyoushi/extensions.git || true
          git fetch upstream

      - name: Update selected files from upstream (sync)
        run: |
          git checkout upstream/repo -- icon index.html index.json index.min.json index.pb repo.json index.beta.json index.beta.pb release-assets.json
          git checkout . && git status --porcelain

      - name: Restore local README
        run: |
          if [ -f /tmp/README.local ]; then
            mv /tmp/README.local README.md
          fi
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
           python-version: "3.11"
           
      - name: Install dependencies
        run: |
          pip install "protobuf>=7.35.1"

      - name: Filter index.pb
        run: |
          python .github/workflows/scripts/filter_pb.py
      

      - name: Commit & push changes
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add icon index.html index.json index.min.json index.pb repo.json index.beta.json index.beta.pb release-assets.json README.md
          git commit -m "Update extensions & filter NSFW (keep README)" || exit 0
          git push
